name: niall
favicon: null
layout_spectrum: 0.8605472252238542
typography_spectrum: 0.721278817858547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9646201014984399
  lightness: 0.6085927665699273
  saturation: 0.8794973557814956
  rhythmicContrast: 0.01890150923281908
purpose: []
