name: niall
favicon: null
layout_spectrum: 0.46473
typography_spectrum: 0.51378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d589a3'
    - '#afc2ce'
    - '#427185'
    - '#0a0e0d'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
